#!/bin/bash

# Update and deploy reports.

SOURCE_DIR=~/src/cspace-deployment
TOOLS_DIR=$SOURCE_DIR/Tools
DEPLOYMENT_NAME=`csname`
REPORT_DIR=$CATALINA_HOME/cspace/reports

cd $TOOLS_DIR

echo "Updating reports..."

if ! git pull; then
	echo "ERROR: Failed to pull updates"
	exit 1
fi

echo "Deploying reports..."

cp reports/$DEPLOYMENT_NAME/*.jrxml $REPORT_DIR
cp reports/$DEPLOYMENT_NAME/images/* ~/tomcat7/webapps/reports/images

if ls $REPORT_DIR/*.jasper &> /dev/null; then
	rm $REPORT_DIR/*.jasper
fi

echo "Reports for $DEPLOYMENT_NAME deployed"
