#!/bin/bash

# Stop the CollectionSpace tomcat service. An attempt is made to determine if the server is in use. If
# it is, the server is not stopped, unless the force (-f) flag is supplied.

if [[ -z $CS_MIN_IDLE_TIME ]]; then
	CS_MIN_IDLE_TIME=600 # Seconds of inactivity required
fi

FORCE=false
IDLE_CHECK=false
OPTIND=1

if [[ -z `csuptime` ]]; then
	echo "CollectionSpace is not running"
	exit 0
fi

while getopts "f?" opt; do
	case "$opt" in
	f) FORCE=true
	   ;;
	esac
done

if [[ $FORCE == true ]]; then
	IDLE_CHECK=true
else
	idle_time=`csidletime`

	if [[ -z idle_time ]]; then
		IDLE_CHECK=true
	else
		if (( idle_time > CS_MIN_IDLE_TIME )); then
			IDLE_CHECK=true
		fi
	fi
fi

if [[ $IDLE_CHECK == true ]]; then
	echo 'Stopping CollectionSpace...'
	sudo /bin/systemctl stop `csservname`
else
	echo "ERROR: CollectionSpace user activity detected. Use -f to force."
	exit 1
fi
