#!/bin/bash

# Start the CollectionSpace tomcat service.

if [[ -n `csuptime` ]]; then
	echo "CollectionSpace is already running"
	exit 0
fi

echo 'Starting CollectionSpace...'

sudo /bin/systemctl start `csservname`
