#!/bin/bash

# Print the version number of CollectionSpace that is currently installed.

VERSION_MESSAGE_ID=footer.release
VERSION_MESSAGE_PATTERN="'$VERSION_MESSAGE_ID': '.*?\\((.*?)\\)'"
MESSAGE_FILE=$CATALINA_HOME/webapps/ROOT/index.html
VERSION_MESSAGE=`grep $VERSION_MESSAGE_ID $MESSAGE_FILE`

if [[ $VERSION_MESSAGE =~ $VERSION_MESSAGE_PATTERN ]]; then
	version=${BASH_REMATCH[1]}
	echo $version
fi
